# -*- coding: utf-8 -*-
"""Yolov3-Darknet

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1esTb6_MIngKGV_TU2gNLp9kI7fo5a3sV
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd drive
# %cd MyDrive
# %cd darknet

!ls

# !make

!./darknet detector train custom_data/detector.data custom_data/cfg/yolov3-custom.cfg darknet53.conv.74 -dont_show

!chmod +x ./darknet

!./darknet detector train custom_data/detector.data custom_data/cfg/yolov3-custom.cfg backup/yolov3-custom_3600.weights -dont_show

!./darknet detector test custom_data/detector.data custom_data/cfg/yolov3-custom2.cfg backup/yolov3-custom2_2000.weights custom_data/test/test1/DJI_0528_JPG.rf.f271180da4406abec44e765177c81dc8.jpg -dont_show
from IPython.display import Image
from google.colab import files
files.download("predictions.jpg")
Image('predictions.jpg')

# !wget https://pjreddie.com/media/files/yolov3.weights

# !wget https://pjreddie.com/media/files/darknet53.conv.74

import random
import os
import subprocess
import sys

def split_data_set(image_dir):

    f_val = open("custom_data/test.txt", 'w')
    f_train = open("custom_data/train.txt", 'w')
    
    path, dirs, files = next(os.walk(image_dir))
    data_size = len(files)

    ind = 0
    data_test_size = int(0.1 * data_size)
    test_array = random.sample(range(data_size), k=data_test_size)
    
    for f in os.listdir(image_dir):
        if(f.split(".")[3] == "jpg"):
            f_train.write("custom_data/images"+'/'+f+'\n')

split_data_set("custom_data/upload")

WINDOWS_LINE_ENDING = b'\r\n'
UNIX_LINE_ENDING = b'\n'

sou="custom_data/train.txt"
file_path = sou

with open(file_path, 'rb') as open_file:
    content = open_file.read()

content = content.replace(WINDOWS_LINE_ENDING, UNIX_LINE_ENDING)

with open(file_path, 'wb') as open_file:
    open_file.write(content)

